// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znlokpotuvjfqvelcned.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubG9rcG90dXZqZnF2ZWxjbmVkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzkzODMwNywiZXhwIjoyMDUzNTE0MzA3fQ.DAexjfE-RP_J423mjCOO5nfceNEtL6RAs6Kzu0oYUgo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);