// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znlokpotuvjfqvelcned.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubG9rcG90dXZqZnF2ZWxjbmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4NzI2NjgsImV4cCI6MjAyNjQ0ODY2OH0.vxjVESYX6CWxKqcHC5GXQCxgXMqQiZGFYtZNY_Iy0Oc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);